'use strict';
const sample=[
["McDonald's","McDouble",3.29,400,22],["McDonald's","McChicken",2.99,400,14],["McDonald's","Small fries",2.49,230,3],
["Taco Bell","Bean burrito",1.99,360,13],["Taco Bell","Cheesy bean & rice burrito",1.49,420,9],["Taco Bell","Chicken quesadilla",5.49,510,26],
["Wendy's","Jr. bacon cheeseburger",3.49,370,18],["Wendy's","Crispy chicken sandwich",2.49,330,14],["Wendy's","Small chili",3.29,240,16],
["Chick-fil-A","Chicken sandwich",5.49,420,29],["Chick-fil-A","8-count nuggets",5.29,250,27],["Chick-fil-A","Medium waffle fries",2.99,420,5],
["Chipotle","Chicken burrito bowl",9.25,660,45],["Chipotle","Veggie burrito bowl",8.75,620,17],
["Whataburger","Whataburger",5.79,590,29],["Whataburger","Justaburger",3.29,310,14],["Whataburger","Small fries",2.39,280,3]
];
let menu=sample.map((x,i)=>({id:i,restaurant:x[0],name:x[1],price:Math.round(x[2]*100),calories:x[3],protein:x[4],source:'sample'}));
let selected=new Set(menu.map(x=>x.restaurant));
const $=id=>document.getElementById(id), money=c=>'$'+(c/100).toFixed(2), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function restaurants(){ $('restaurants').innerHTML=[...new Set(menu.map(x=>x.restaurant))].map((r,i)=>`<label class="check"><input type="checkbox" data-restaurant="${esc(r)}" ${selected.has(r)?'checked':''}><span>${esc(r)}</span><b>${menu.filter(x=>x.restaurant===r).length}</b></label>`).join(''); }
function orders(items,budget,min,combos){const all=[];const add=(a,b)=>{const price=a.price+(b?.price||0),calories=a.calories+(b?.calories||0),protein=a.protein+(b?.protein||0);if(price<=budget&&calories>=min)all.push({restaurant:a.restaurant,name:b?(a.id===b.id?'2 × '+a.name:a.name+' + '+b.name):a.name,price,calories,protein,source:a.source,cpd:calories/(price/100),ppd:protein/(price/100)});};items.forEach((a,i)=>{add(a);if(combos)items.slice(i).forEach(b=>{if(a.restaurant===b.restaurant)add(a,b);});});return all;}
function rank(all,goal){const mc=Math.max(1,...all.map(x=>x.cpd)),mp=Math.max(1,...all.map(x=>x.ppd));all.forEach(x=>x.score=goal==='price'?-x.price:goal==='protein'?x.ppd:goal==='calories'?x.cpd:50*(x.cpd/mc+x.ppd/mp));return all.sort((a,b)=>b.score-a.score||a.price-b.price||a.name.localeCompare(b.name));}
function render(){const raw=Number($('budget').value),budget=Number.isFinite(raw)?Math.max(0,Math.round(raw*100)):0;const goal=$('goal').value;const list=rank(orders(menu.filter(x=>selected.has(x.restaurant)),budget,Number($('minimum').value),$('combos').checked),goal);$('count').textContent=list.length+' matching orders';if(!list.length){$('winner').innerHTML='<div class="empty"><h3>No orders fit just yet.</h3><p>Try a higher budget, a lower calorie minimum, or select another restaurant.</p></div>';$('cards').innerHTML='';return;}const w=list[0];const labels={balanced:'BEST BALANCED VALUE',protein:'MOST PROTEIN PER DOLLAR',calories:'MOST CALORIES PER DOLLAR',price:'LOWEST PRICE'};const ratio=x=>goal==='protein'?x.ppd.toFixed(1)+'g protein / $':goal==='calories'?Math.round(x.cpd)+' cal / $':goal==='price'?money(x.price)+' total':Math.round(x.score)+'/100 value score';$('winner').innerHTML=`<article class="winner"><span class="badge">✦ ${labels[goal]}</span><div class="winner-top"><div><div class="restaurant">${esc(w.restaurant)} · ${w.source==='sample'?'Sample menu':'Your menu'}</div><h3>${esc(w.name)}</h3></div><div class="price">${money(w.price)}<small>${money(budget-w.price)} left over</small></div></div><div class="metrics"><div class="metric"><strong>${w.calories}</strong><span>total calories</span></div><div class="metric"><strong>${w.protein}g</strong><span>total protein</span></div><div class="metric"><strong>${goal==='protein'?w.ppd.toFixed(1)+'g':goal==='calories'?Math.round(w.cpd):goal==='price'?money(w.price):Math.round(w.score)+'/100'}</strong><span>${goal==='protein'?'protein per dollar':goal==='calories'?'calories per dollar':goal==='price'?'order total':'balanced value score'}</span></div></div><p class="winner-note">${Math.round(w.cpd)} calories and ${w.ppd.toFixed(1)}g protein for every dollar. ${w.source==='sample'?'Check local menu prices before ordering.':'Based on the prices and nutrition you entered.'}</p></article>`;
$('cards').innerHTML=list.slice(1,7).map((x,i)=>`<article class="card"><span class="rank">${String(i+2).padStart(2,'0')}</span><div><div class="restaurant">${esc(x.restaurant)} · ${x.source==='sample'?'Sample':'Your menu'}</div><h3>${esc(x.name)}</h3><div class="stats"><span>${x.calories} cal</span><span>${x.protein}g protein</span><span class="ratio">${ratio(x)}</span></div></div><div class="price">${money(x.price)}</div></article>`).join('')+(list.length>7?`<p class="fine">Showing the top 7 of ${list.length} matching orders. Adjust your filters to explore more.</p>`:'');}
$('restaurants').addEventListener('change',e=>{const r=e.target.dataset.restaurant;if(r){e.target.checked?selected.add(r):selected.delete(r);render();}});['goal','minimum','combos'].forEach(id=>$(id).addEventListener('change',render));$('budget').addEventListener('input',()=>{$('budgetRange').value=Math.min(30,Number($('budget').value));render();});$('budgetRange').addEventListener('input',()=>{$('budget').value=$('budgetRange').value;render();});$('reset').onclick=()=>{$('budget').value=10;$('budgetRange').value=10;$('goal').value='balanced';$('minimum').value='400';$('combos').checked=true;selected=new Set(menu.map(x=>x.restaurant));restaurants();render();};$('openImport').onclick=()=>$('importDialog').showModal();$('closeImport').onclick=()=>$('importDialog').close();
function parseMenu(text,restaurant,start){const lines=text.split('\n').map(x=>x.trim()).filter(Boolean);if(!lines.length)throw Error('Add at least one menu item.');if(lines.length>100)throw Error('Please analyze up to 100 items at a time.');return lines.map((line,i)=>{const p=line.split('|').map(x=>x.trim());if(p.length!==4||!p[0]||!/^\$?\d+(\.\d{1,2})?$/.test(p[1])||!/^\d+(\.\d+)?$/.test(p[2])||!/^\d+(\.\d+)?$/.test(p[3]))throw Error('Line '+(i+1)+': use Name | 5.49 | 460 | 28 (all four fields are required).');const price=Math.round(Number(p[1].replace('$',''))*100),calories=Number(p[2]),protein=Number(p[3]);if(price<=0||price>100000||calories>10000||protein>1000||p[0].length>150)throw Error('Line '+(i+1)+': check the price, nutrition, or item-name length.');return{id:start+i,restaurant,name:p[0],price,calories,protein,source:'custom'};});}
$('importForm').onsubmit=e=>{e.preventDefault();try{const name=$('restaurantName').value.trim();if(!name)throw Error('Enter a restaurant name.');const custom=parseMenu($('menuText').value,name,menu.length?Math.max(...menu.map(x=>x.id))+1:0);menu=menu.filter(x=>x.restaurant!==name).concat(custom);selected=new Set([name]);$('minimum').value='0';$('importError').textContent='';restaurants();render();$('importDialog').close();}catch(err){$('importError').textContent=err.message;}};
restaurants();render();
